#!/usr/bin/env sh
#. "${0%/*}/h"

#"$(dirname -- "$0")/_/husky.sh"



./vendor/bin/phpstan

if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar...";
fi


STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACH | grep ".php\{0,1\}$")

for FILE in $STAGED_FILES
do
    .vendor/bin/pint "${FILE}"
    git add "${FILE}"
done;